import * as React from "react"

import { AppShell } from "@/components"
import { Inter } from "next/font/google"

import "@/styles/globals.css"

const inter = Inter({ subsets: ["latin"] })

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
    return (
        <html
            lang="en"
            data-theme="night"
            className={inter.className}
        >
            <body>
                <AppShell />
                {/* <main className="flex min-h-screen flex-col items-center justify-between p-24"> */}
                <main className="px-6">{children}</main>
            </body>
        </html>
    )
}
